from _typeshed import Incomplete

class VarLibError(Exception): ...
class VarLibValidationError(VarLibError): ...

class VarLibMergeError(VarLibError):
    merger: Incomplete
    stack: Incomplete
    cause: Incomplete
    def __init__(self, merger: Incomplete | None = ..., **kwargs) -> None: ...
    @property
    def reason(self): ...
    @property
    def offender(self): ...
    @property
    def details(self): ...

class ShouldBeConstant(VarLibMergeError):
    @property
    def details(self): ...

class FoundANone(VarLibMergeError):
    @property
    def offender(self): ...
    @property
    def details(self): ...

class NotANone(VarLibMergeError):
    @property
    def offender(self): ...
    @property
    def details(self): ...

class MismatchedTypes(VarLibMergeError): ...
class LengthsDiffer(VarLibMergeError): ...
class KeysDiffer(VarLibMergeError): ...
class InconsistentGlyphOrder(VarLibMergeError): ...
class InconsistentExtensions(VarLibMergeError): ...

class UnsupportedFormat(VarLibMergeError):
    stack: Incomplete
    def __init__(self, merger: Incomplete | None = ..., **kwargs) -> None: ...
    @property
    def reason(self): ...

class InconsistentFormats(UnsupportedFormat): ...
class VarLibCFFMergeError(VarLibError): ...

class VarLibCFFDictMergeError(VarLibCFFMergeError):
    args: Incomplete
    def __init__(self, key, value, values) -> None: ...

class VarLibCFFPointTypeMergeError(VarLibCFFMergeError):
    args: Incomplete
    def __init__(
        self, point_type, pt_index, m_index, default_type, glyph_name
    ) -> None: ...

class VarLibCFFHintTypeMergeError(VarLibCFFMergeError):
    args: Incomplete
    def __init__(
        self, hint_type, cmd_index, m_index, default_type, glyph_name
    ) -> None: ...

class VariationModelError(VarLibError): ...
