from fontTools.misc.dictTools import hashdict as hashdict
from fontTools.misc.intTools import popCount as popCount
from fontTools.otlLib.builder import buildLookup as buildLookup
from fontTools.otlLib.builder import (
    buildSingleSubstSubtable as buildSingleSubstSubtable,
)
from fontTools.ttLib import newTable as newTable

from .errors import VarLibError as VarLibError
from .errors import VarLibValidationError as VarLibValidationError

def addFeatureVariations(
    font, conditionalSubstitutions, featureTag: str = ...
) -> None: ...
def overlayFeatureVariations(conditionalSubstitutions): ...
def overlayBox(top, bot): ...
def cleanupBox(box): ...
def addFeatureVariationsRaw(
    font, table, conditionalSubstitutions, featureTag: str = ...
) -> None: ...
def buildGSUB(): ...
def makeSubstitutionsHashable(conditionalSubstitutions): ...
def buildSubstitutionLookups(gsub, allSubstitutions): ...
def buildFeatureVariations(featureVariationRecords): ...
def buildFeatureRecord(featureTag, lookupListIndices): ...
def buildFeatureVariationRecord(conditionTable, substitutionRecords): ...
def buildFeatureTableSubstitutionRecord(featureIndex, lookupListIndices): ...
def buildConditionTable(axisIndex, filterRangeMinValue, filterRangeMaxValue): ...
def sortFeatureList(table) -> None: ...
def remapFeatures(table, featureRemap) -> None: ...
