from _typeshed import Incomplete
from fontTools.designspaceLib import DesignSpaceDocument as DesignSpaceDocument
from fontTools.varLib.models import VariationModel as VariationModel
from fontTools.varLib.models import supportScalar as supportScalar
from mpl_toolkits.mplot3d import axes3d as axes3d

log: Incomplete

def stops(support, count: int = ...): ...
def plotLocations(locations, fig, names: Incomplete | None = ..., **kwargs) -> None: ...
def plotDocument(doc, fig, **kwargs) -> None: ...
def plotModelFromMasters(model, masterValues, fig, **kwargs) -> None: ...
def main(args: Incomplete | None = ...) -> None: ...
