from _typeshed import Incomplete
from fontTools.varLib.models import VariationModel as VariationModel
from fontTools.varLib.models import normalizeValue as normalizeValue

def Location(loc): ...

class VariableScalar:
    model_pool: Incomplete
    @classmethod
    def clear_cache(cls) -> None: ...
    values: Incomplete
    axes: Incomplete
    def __init__(self, location_value=...) -> None: ...
    @property
    def does_vary(self): ...
    @property
    def axes_dict(self): ...
    def fix_location(self, location): ...
    def add_value(self, location, value) -> None: ...
    def fix_all_locations(self) -> None: ...
    @property
    def default(self): ...
    def value_at_location(self, location): ...
    @property
    def model(self): ...
    def get_deltas_and_supports(self): ...
    def add_to_variation_store(self, store_builder): ...
