from _typeshed import Incomplete

from . import DefaultTable as DefaultTable

log: Incomplete

class table__l_o_c_a(DefaultTable.DefaultTable):
    dependencies: Incomplete
    locations: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def set(self, locations) -> None: ...
    def toXML(self, writer, ttFont) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
