from _typeshed import Incomplete
from fontTools.misc.textTools import bytesjoin as bytesjoin
from fontTools.misc.textTools import safeEval as safeEval
from fontTools.misc.textTools import tobytes as tobytes

from . import DefaultTable as DefaultTable

class table__l_t_a_g(DefaultTable.DefaultTable):
    tags: Incomplete
    def __init__(self, tag: Incomplete | None = ...) -> None: ...
    def addTag(self, tag): ...
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
