from _typeshed import Incomplete
from fontTools.misc.textTools import safeEval as safeEval

from . import DefaultTable as DefaultTable

class table_C_O_L_R_(DefaultTable.DefaultTable):
    version: Incomplete
    ColorLayers: Incomplete
    table: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def __getitem__(self, glyphName): ...
    def __setitem__(self, glyphName, value) -> None: ...
    def __delitem__(self, glyphName) -> None: ...

class LayerRecord:
    name: Incomplete
    colorID: Incomplete
    def __init__(
        self, name: Incomplete | None = ..., colorID: Incomplete | None = ...
    ) -> None: ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, eltname, attrs, content, ttFont) -> None: ...
