from _typeshed import Incomplete

from . import DefaultTable as DefaultTable

class table_D__e_b_g(DefaultTable.DefaultTable):
    data: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
