from _typeshed import Incomplete
from fontTools.misc.textTools import Tag as Tag
from fontTools.ttLib import getClassTag as getClassTag

class DefaultTable:
    dependencies: Incomplete
    tableTag: Incomplete
    def __init__(self, tag: Incomplete | None = ...) -> None: ...
    data: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont, **kwargs) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
