from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.textTools import bytesjoin as bytesjoin
from fontTools.misc.textTools import safeEval as safeEval

from . import DefaultTable as DefaultTable
from .BitmapGlyphMetrics import BigGlyphMetrics as BigGlyphMetrics
from .BitmapGlyphMetrics import SmallGlyphMetrics as SmallGlyphMetrics
from .BitmapGlyphMetrics import bigGlyphMetricsFormat as bigGlyphMetricsFormat
from .BitmapGlyphMetrics import smallGlyphMetricsFormat as smallGlyphMetricsFormat

log: Incomplete
eblcHeaderFormat: str
bitmapSizeTableFormatPart1: str
sbitLineMetricsFormat: str
bitmapSizeTableFormatPart2: str
indexSubTableArrayFormat: str
indexSubTableArraySize: Incomplete
indexSubHeaderFormat: str
indexSubHeaderSize: Incomplete
codeOffsetPairFormat: str
codeOffsetPairSize: Incomplete

class table_E_B_L_C_(DefaultTable.DefaultTable):
    dependencies: Incomplete
    def getIndexFormatClass(self, indexFormat): ...
    strikes: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    numSizes: Incomplete
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    version: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class Strike:
    bitmapSizeTable: Incomplete
    indexSubTables: Incomplete
    def __init__(self) -> None: ...
    def toXML(self, strikeIndex, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont, locator) -> None: ...

class BitmapSizeTable:
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class SbitLineMetrics:
    def toXML(self, name, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

class EblcIndexSubTable:
    data: Incomplete
    ttFont: Incomplete
    def __init__(self, data, ttFont) -> None: ...
    def __getattr__(self, attr): ...
    def ensureDecompiled(self, recurse: bool = ...) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    imageFormat: Incomplete
    firstGlyphIndex: Incomplete
    lastGlyphIndex: Incomplete
    names: Incomplete
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def writeMetrics(self, writer, ttFont) -> None: ...
    def readMetrics(self, name, attrs, content, ttFont) -> None: ...
    def padBitmapData(self, data): ...
    def removeSkipGlyphs(self): ...

class FixedSizeIndexSubTableMixin:
    def writeMetrics(self, writer, ttFont) -> None: ...
    imageSize: Incomplete
    metrics: Incomplete
    def readMetrics(self, name, attrs, content, ttFont) -> None: ...
    def padBitmapData(self, data): ...

class eblc_index_sub_table_1(EblcIndexSubTable): ...

class eblc_index_sub_table_2(FixedSizeIndexSubTableMixin, EblcIndexSubTable):
    metrics: Incomplete
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

class eblc_index_sub_table_3(EblcIndexSubTable): ...

class eblc_index_sub_table_4(EblcIndexSubTable):
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

class eblc_index_sub_table_5(FixedSizeIndexSubTableMixin, EblcIndexSubTable):
    origDataLen: int
    locations: Incomplete
    names: Incomplete
    def decompile(self) -> None: ...
    imageDataOffset: Incomplete
    def compile(self, ttFont): ...

eblc_sub_table_classes: Incomplete
