from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.fixedTools import floatToFixedToStr as floatToFixedToStr
from fontTools.misc.textTools import safeEval as safeEval

from . import DefaultTable as DefaultTable
from . import grUtils as grUtils

Glat_format_0: str
Glat_format_3: str
Glat_format_1_entry: str
Glat_format_23_entry: str
Glat_format_3_octabox_metrics: str
Glat_format_3_subbox_entry: str

class _Object: ...
class _Dict(dict): ...

class table_G__l_a_t(DefaultTable.DefaultTable):
    scheme: int
    def __init__(self, tag: Incomplete | None = ...) -> None: ...
    version: Incomplete
    hasOctaboxes: Incomplete
    attributes: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def decompileAttributes12(self, data, fmt): ...
    def decompileAttributes3(self, data): ...
    compression: Incomplete
    def compile(self, ttFont): ...
    def compileAttributes12(self, attrs, fmt): ...
    def compileAttributes3(self, attrs): ...
    def toXML(self, writer, ttFont): ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
