from _typeshed import Incomplete
from fontTools.misc import sstruct as sstruct
from fontTools.misc.roundTools import otRound as otRound
from fontTools.misc.textTools import binary2num as binary2num
from fontTools.misc.textTools import num2binary as num2binary
from fontTools.misc.textTools import safeEval as safeEval
from fontTools.ttLib.tables import DefaultTable as DefaultTable

log: Incomplete
panoseFormat: str

class Panose:
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...

OS2_format_0: str
OS2_format_1_addition: str
OS2_format_2_addition: Incomplete
OS2_format_5_addition: Incomplete
bigendian: str
OS2_format_1: Incomplete
OS2_format_2: Incomplete
OS2_format_5: Incomplete

class table_O_S_2f_2(DefaultTable.DefaultTable):
    dependencies: Incomplete
    panose: Incomplete
    def decompile(self, data, ttFont) -> None: ...
    def compile(self, ttFont): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    usFirstCharIndex: Incomplete
    usLastCharIndex: Incomplete
    def updateFirstAndLastCharIndex(self, ttFont) -> None: ...
    @property
    def usMaxContex(self): ...
    usMaxContext: Incomplete
    @usMaxContex.setter
    def usMaxContex(self, value) -> None: ...
    @property
    def fsFirstCharIndex(self): ...
    @fsFirstCharIndex.setter
    def fsFirstCharIndex(self, value) -> None: ...
    @property
    def fsLastCharIndex(self): ...
    @fsLastCharIndex.setter
    def fsLastCharIndex(self, value) -> None: ...
    def getUnicodeRanges(self): ...
    def setUnicodeRanges(self, bits) -> None: ...
    def recalcUnicodeRanges(self, ttFont, pruneOnly: bool = ...): ...
    xAvgCharWidth: Incomplete
    def recalcAvgCharWidth(self, ttFont): ...

OS2_UNICODE_RANGES: Incomplete

def intersectUnicodeRanges(unicodes, inverse: bool = ...): ...
