from _typeshed import Incomplete
from fontTools.misc.textTools import binary2num as binary2num
from fontTools.misc.textTools import num2binary as num2binary
from fontTools.misc.textTools import readHex as readHex
from fontTools.misc.textTools import strjoin as strjoin

log: Incomplete
streamInstructions: Incomplete
instructions: Incomplete

def bitRepr(value, bits): ...

streamOpcodeDict: Incomplete
streamMnemonicDict: Incomplete
opcodeDict: Incomplete
mnemonicDict: Incomplete

class tt_instructions_error(Exception):
    error: Incomplete
    def __init__(self, error) -> None: ...

class Program:
    def __init__(self) -> None: ...
    bytecode: Incomplete
    def fromBytecode(self, bytecode) -> None: ...
    assembly: Incomplete
    def fromAssembly(self, assembly) -> None: ...
    def getBytecode(self): ...
    def getAssembly(self, preserve: bool = ...): ...
    def toXML(self, writer, ttFont) -> None: ...
    def fromXML(self, name, attrs, content, ttFont) -> None: ...
    def __bool__(self) -> bool: ...
    __nonzero__: Incomplete
    def __eq__(self, other): ...
    def __ne__(self, other): ...
