from _typeshed import Incomplete
from fontTools.pens.basePen import BasePen

class PointInsidePen(BasePen):
    def __init__(self, glyphSet, testPoint, evenOdd: bool = ...) -> None: ...
    testPoint: Incomplete
    evenOdd: Incomplete
    firstPoint: Incomplete
    intersectionCount: int
    def setTestPoint(self, testPoint, evenOdd: bool = ...) -> None: ...
    def getWinding(self): ...
    def getResult(self): ...
