from typing import Callable

from _typeshed import Incomplete
from fontTools.pens.basePen import BasePen as BasePen

def pointToString(pt, ntos=...): ...

class SVGPathPen(BasePen):
    def __init__(self, glyphSet, ntos: Callable[[float], str] = ...) -> None: ...
    def getCommands(self): ...

def main(args: Incomplete | None = ...) -> None: ...
