from _typeshed import Incomplete
from fontTools.pens.basePen import AbstractPen

class TeePen(AbstractPen):
    pens: Incomplete
    def __init__(self, *pens) -> None: ...
    def moveTo(self, p0) -> None: ...
    def lineTo(self, p1) -> None: ...
    def qCurveTo(self, *points) -> None: ...
    def curveTo(self, *points) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
    def addComponent(self, glyphName, transformation) -> None: ...
