from _typeshed import Incomplete
from fontTools.pens.filterPen import FilterPen, FilterPointPen

class TransformPen(FilterPen):
    def __init__(self, outPen, transformation) -> None: ...
    def moveTo(self, pt) -> None: ...
    def lineTo(self, pt) -> None: ...
    def curveTo(self, *points) -> None: ...
    def qCurveTo(self, *points) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
    def addComponent(self, glyphName, transformation) -> None: ...

class TransformPointPen(FilterPointPen):
    def __init__(self, outPointPen, transformation) -> None: ...
    def addPoint(
        self,
        pt,
        segmentType: Incomplete | None = ...,
        smooth: bool = ...,
        name: Incomplete | None = ...,
        **kwargs
    ) -> None: ...
    def addComponent(self, baseGlyphName, transformation, **kwargs) -> None: ...
