repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.0rc1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: local
    hooks:
      - id: black-isort
        name: black & isort
        entry: poetry run black .; poetry run isort .
        language: system
        types: [ python ]
        pass_filenames: false
