repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [ python ]
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [ python ]
        pass_filenames: false
