repos:
  - repo: local
    hooks:
      - id: black-isort
        name: black & isort
        entry: poetry run black .; poetry run isort .
        language: system
        types: [ python ]
        pass_filenames: false
