language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install pillow blessed schema sympy numpy codecov
  - mkdir tiles
script:
  - pytest test.py
  - coverage run test.py --concurrency=multiprocessing
  - coverage combine
after_success:
  - codecov
branches:
  only:
  - main
jobs:
  allow_failures:
  - python: "3.7"
  fast_finish: true
