from _typeshed import Incomplete
from fontTools.pens.basePen import AbstractPen

class GetSegmentsPen(AbstractPen):
    segments: Incomplete
    def __init__(self) -> None: ...
    def moveTo(self, pt) -> None: ...
    def lineTo(self, pt) -> None: ...
    def qCurveTo(self, *points) -> None: ...
    def curveTo(self, *points) -> None: ...
    def closePath(self) -> None: ...
    def endPath(self) -> None: ...
    def addComponent(self, glyphName, transformation) -> None: ...

def fonts_to_quadratic(
    fonts,
    max_err_em: Incomplete | None = ...,
    max_err: Incomplete | None = ...,
    reverse_direction: bool = ...,
    stats: Incomplete | None = ...,
    dump_stats: bool = ...,
    remember_curve_type: bool = ...,
): ...
def font_to_quadratic(font, **kwargs): ...
