def convertUFO1OrUFO2KerningToUFO3Kerning(kerning, groups, glyphSet=...): ...
def findKnownKerningGroups(groups): ...
def makeUniqueGroupName(name, groupNames, counter: int = ...): ...
def test() -> None: ...
