name: Mise
description: Mise

inputs:
  envs:
    description: envs
    default: "lint"
  cache:
    description: cache
    default: "true"

outputs:
  mise-action:
    description: mise-action output
    value: ${{ toJSON(steps.mise-action.outputs) }}

runs:
  using: composite
  steps:
    - id: mise-env
      shell: bash
      run: echo "MISE_ENV=$ENVS" > "$GITHUB_ENV"  # zizmor: ignore[github-env]
      env:
        ENVS: ${{ inputs.envs }}

    - id: mise-action
      uses: jdx/mise-action@2d8d4cafcbd33be2ea37d2b6f5ad595363d1f1ca # v5.1.1
      with:
        version: v2026.10.3
        cache: ${{ inputs.cache }}
