name: Mise
description: Mise

inputs:
  envs:
    description: envs
    default: "lint"
  cache:
    description: cache
    default: "true"

outputs:
  mise-action:
    description: mise-action output
    value: ${{ toJSON(steps.mise-action.outputs) }}

runs:
  using: composite
  steps:
    - id: mise-env
      shell: bash
      run: echo "MISE_ENV=$ENVS" > "$GITHUB_ENV"  # zizmor: ignore[github-env]
      env:
        ENVS: ${{ inputs.envs }}

    - id: mise-action
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
      with:
        version: v2026.6.0
        cache: ${{ inputs.cache }}
