name: Mise
description: Mise

inputs:
  envs:
    description: envs
    default: "lint"
  cache:
    description: cache
    default: "true"

outputs:
  mise-action:
    description: mise-action output
    value: ${{ toJSON(steps.mise-action.outputs) }}

runs:
  using: composite
  steps:
    - id: mise-env
      shell: bash
      run: echo "MISE_ENV=$ENVS" > "$GITHUB_ENV"  # zizmor: ignore[github-env]
      env:
        ENVS: ${{ inputs.envs }}

    - id: mise-action
      uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      with:
        version: v2026.9.17
        cache: ${{ inputs.cache }}
