from _typeshed import Incomplete
from fontTools.ttLib import TTFont as TTFont

class missingdict(dict):
    missing_func: Incomplete
    def __init__(self, missing_func) -> None: ...
    def __missing__(self, v): ...

def cumSum(f, op=..., start: int = ..., decreasing: bool = ...): ...
def byteCost(widths, default, nominal): ...
def optimizeWidthsBruteforce(widths): ...
def optimizeWidths(widths): ...
def main(args: Incomplete | None = ...) -> None: ...
