from _typeshed import Incomplete

identifierRE: Incomplete
charRE: Incomplete
kernRE: Incomplete
compositeRE: Incomplete
componentRE: Incomplete
preferredAttributeOrder: Incomplete

class error(Exception): ...

class AFM:
    def __init__(self, path: Incomplete | None = ...) -> None: ...
    def read(self, path) -> None: ...
    def parsechar(self, rest) -> None: ...
    def parsekernpair(self, rest) -> None: ...
    def parseattr(self, word, rest) -> None: ...
    def parsecomposite(self, rest) -> None: ...
    def write(self, path, sep: str = ...): ...
    def has_kernpair(self, pair): ...
    def kernpairs(self): ...
    def has_char(self, char): ...
    def chars(self): ...
    def comments(self): ...
    def addComment(self, comment) -> None: ...
    def addComposite(self, glyphName, components) -> None: ...
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None: ...
    def __delattr__(self, attr) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...

def readlines(path): ...
def writelines(path, lines, sep: str = ...) -> None: ...
