from _typeshed import Incomplete
from fontTools.merge.options import Options as Options

class Merger:
    options: Incomplete
    def __init__(self, options: Incomplete | None = ...) -> None: ...
    duplicateGlyphsPerFont: Incomplete
    fonts: Incomplete
    def merge(self, fontfiles): ...
    def mergeObjects(self, returnTable, logic, tables): ...

def main(args: Incomplete | None = ...): ...
