from _typeshed import Incomplete
from fontTools.ttLib.tables.DefaultTable import DefaultTable as DefaultTable

log: Incomplete

def add_method(*clazzes, **kwargs): ...
def mergeObjects(lst): ...
def merge(self, m, tables): ...
