from _typeshed import Incomplete
from fontTools import ttLib as ttLib
from fontTools.merge.base import add_method as add_method
from fontTools.merge.base import mergeObjects as mergeObjects
from fontTools.merge.util import *
from fontTools.ttLib.tables import otTables as otTables
from fontTools.ttLib.tables.DefaultTable import DefaultTable as DefaultTable

log: Incomplete

def mergeLookupLists(lst): ...
def mergeFeatures(lst): ...
def mergeFeatureLists(lst): ...
def mergeLangSyses(lst): ...
def mergeScripts(lst): ...
def mergeScriptRecords(lst): ...
def merge(self, m, tables): ...
def mapLookups(self, lookupMap) -> None: ...
def layoutPreMerge(font) -> None: ...
def layoutPostMerge(font) -> None: ...
