from _typeshed import Incomplete

class Options:
    class UnknownOptionError(Exception): ...
    verbose: bool
    timing: bool
    drop_tables: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def set(self, **kwargs) -> None: ...
    def parse_opts(self, argv, ignore_unknown=...): ...
