from _typeshed import Incomplete
from fontTools.misc.timeTools import timestampNow as timestampNow
from fontTools.ttLib.tables.DefaultTable import DefaultTable as DefaultTable

log: Incomplete

def equal(lst): ...
def first(lst): ...
def recalculate(lst): ...
def current_time(lst): ...
def bitwise_and(lst): ...
def bitwise_or(lst): ...
def avg_int(lst): ...
def onlyExisting(func): ...
def sumLists(lst): ...
def sumDicts(lst): ...
def mergeBits(bitmap): ...

class AttendanceRecordingIdentityDict:
    l: Incomplete
    d: Incomplete
    s: Incomplete
    def __init__(self, lst) -> None: ...
    def __getitem__(self, v): ...

class GregariousIdentityDict:
    l: Incomplete
    s: Incomplete
    def __init__(self, lst) -> None: ...
    def __getitem__(self, v): ...

class NonhashableDict:
    d: Incomplete
    def __init__(self, keys, values: Incomplete | None = ...) -> None: ...
    def __getitem__(self, k): ...
    def __setitem__(self, k, v) -> None: ...
    def __delitem__(self, k) -> None: ...
