from _typeshed import Incomplete
from dill._dill import IS_PYPY as IS_PYPY
from dill.source import getimportable as getimportable
from dill.source import getname as getname
from dill.source import getsource as getsource
from dill.source import likely_import as likely_import

PY310b: int
f: Incomplete

def g(x): ...
def h(x): ...

class Foo:
    def bar(self, x): ...

def add(x, y): ...

squared: Incomplete

class Bar: ...

def test_getsource() -> None: ...
def test_itself() -> None: ...
def test_builtin() -> None: ...
def test_imported() -> None: ...
def test_dynamic() -> None: ...
def test_classes() -> None: ...
def test_importable() -> None: ...
def test_numpy() -> None: ...
def test_foo() -> None: ...
