def function_a(a): ...
def function_b(b, b1): ...
def function_c(c, c1: int = ...): ...
def function_d(d, d1, d2: int = ...): ...

globalvar: int

def function_with_cache(x): ...
def function_with_unassigned_variable(): ...
def test_issue_510(): ...
def test_functions() -> None: ...
def test_code_object() -> None: ...
