from _typeshed import Incomplete

fname: str
rand_chars: Incomplete
buffer_error: Incomplete
dne_error: Incomplete

def write_randomness(number: int = ...): ...
def trunc_file() -> None: ...
def throws(op, args, exc): ...
def teardown_module() -> None: ...
def bench(strictio, fmode, skippypy) -> None: ...
def test_nostrictio_handlefmode() -> None: ...
def test_nostrictio_filefmode() -> None: ...
def test_nostrictio_contentsfmode() -> None: ...
