from _typeshed import Incomplete

def wtf(x, y, z): ...
def quad(a: int = ..., b: int = ..., c: int = ...): ...
def double_add(*args): ...

fx: Incomplete

def quad_factory(a: int = ..., b: int = ..., c: int = ...): ...
def quadish(x): ...

quadratic: Incomplete

def doubler(f): ...
def quadruple(x): ...
def test_mixins() -> None: ...
