from _typeshed import Incomplete

def f(func): ...
def f2() -> None: ...
def test_decorated() -> None: ...

class SomeUnreferencedUnpicklableClass:
    def __reduce__(self) -> None: ...

unpicklable: Incomplete

def test_normal(): ...
def tests() -> None: ...
def test_doctest() -> None: ...
