from dill import load_types as load_types
from dill import objects as objects

verbose: bool

def test_dict_contents() -> None: ...

class _d: ...

def test_class_descriptors() -> None: ...
def test_class() -> None: ...
def test_frame_related(): ...
def test_typing() -> None: ...
