def get_fun_with_strftime(): ...
def get_fun_with_strftime2(): ...
def test_doc_dill_issue_219() -> None: ...
def get_fun_with_internal_import(): ...
def test_method_with_internal_import_should_work() -> None: ...
