from _typeshed import Incomplete
from dill import check as check
from dill.temp import capture as capture

def raise_check(func, **kwds) -> None: ...

f: Incomplete

def test_simple(verbose: Incomplete | None = ...) -> None: ...
def test_recurse(verbose: Incomplete | None = ...) -> None: ...
def test_byref(verbose: Incomplete | None = ...) -> None: ...
def test_protocol(verbose: Incomplete | None = ...) -> None: ...
def test_python(verbose: Incomplete | None = ...) -> None: ...
