from dill._dill import MAPPING_PROXY_TRICK as MAPPING_PROXY_TRICK
from dill._dill import OLD310 as OLD310
from dill._dill import DictProxyType as DictProxyType

def test_dictproxy() -> None: ...
def test_dictviews() -> None: ...
def test_dictproxy_trick() -> None: ...
