from _typeshed import Incomplete

class Foo:
    def __init__(self) -> None: ...
    data: Incomplete

def test_data_not_none() -> None: ...
def test_data_unchanged() -> None: ...
def test_data_changed() -> None: ...
