from _typeshed import Incomplete
from fontTools.misc.roundTools import otRound as otRound

class Circle:
    centre: Incomplete
    radius: Incomplete
    def __init__(self, centre, radius) -> None: ...
    def round(self): ...
    def inside(self, outer_circle, tolerance=...): ...
    def concentric(self, other): ...
    def move(self, dx, dy) -> None: ...

def round_start_circle_stable_containment(c0, r0, c1, r1): ...
