from _typeshed import Incomplete

class cached_property(property):
    __name__: Incomplete
    __module__: Incomplete
    __doc__: Incomplete
    __func__: Incomplete
    def __init__(
        self, func, name: Incomplete | None = ..., doc: Incomplete | None = ...
    ) -> None: ...
    def __set__(self, obj, value) -> None: ...
    def __get__(self, obj, type: Incomplete | None = ...): ...
