from _typeshed import Incomplete
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import all_types as all_types
from .common import empty as empty
from .common import empty_line_string as empty_line_string
from .common import empty_line_string_z as empty_line_string_z
from .common import empty_point as empty_point
from .common import empty_point_z as empty_point_z
from .common import empty_polygon as empty_polygon
from .common import line_string as line_string
from .common import line_string_nan as line_string_nan
from .common import line_string_z as line_string_z
from .common import point as point

EMPTY_GEOMS: Incomplete
line_string_reversed: Incomplete
PRE_GEOS_390: Incomplete

def make_array(left, right, use_array): ...
def test_assert_geometries_equal(geom, use_array) -> None: ...
def test_assert_geometries_not_equal(geom1, geom2, use_array) -> None: ...
def test_assert_none_equal(use_array) -> None: ...
def test_assert_none_not_equal(use_array) -> None: ...
def test_assert_nan_equal(use_array) -> None: ...
def test_assert_nan_not_equal(use_array) -> None: ...
def test_normalize_true() -> None: ...
def test_normalize_default() -> None: ...
def test_normalize_false() -> None: ...
