from shapely import GeometryCollection as GeometryCollection
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import MultiLineString as MultiLineString
from shapely import Point as Point
from shapely.errors import UnsupportedGEOSVersionError as UnsupportedGEOSVersionError
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import empty_line_string as empty_line_string
from .common import empty_point as empty_point
from .common import line_string as line_string
from .common import linear_ring as linear_ring
from .common import multi_line_string as multi_line_string
from .common import multi_point as multi_point
from .common import multi_polygon as multi_polygon
from .common import point as point
from .common import polygon as polygon

def test_line_interpolate_point_geom_array() -> None: ...
def test_line_interpolate_point_geom_array_normalized() -> None: ...
def test_line_interpolate_point_float_array() -> None: ...
def test_line_interpolate_point_empty(geom, normalized) -> None: ...
def test_line_interpolate_point_invalid_type(geom, normalized) -> None: ...
def test_line_interpolate_point_none() -> None: ...
def test_line_interpolate_point_nan() -> None: ...
def test_line_locate_point_geom_array() -> None: ...
def test_line_locate_point_geom_array2() -> None: ...
def test_line_locate_point_none(normalized) -> None: ...
def test_line_locate_point_empty(normalized) -> None: ...
def test_line_locate_point_invalid_geometry(normalized) -> None: ...
def test_line_merge_geom_array() -> None: ...
def test_line_merge_directed() -> None: ...
def test_line_merge_error() -> None: ...
def test_shared_paths_linestring() -> None: ...
def test_shared_paths_none() -> None: ...
def test_shared_paths_non_linestring() -> None: ...
def test_shortest_line(prepare) -> None: ...
def test_shortest_line_none(prepare) -> None: ...
def test_shortest_line_empty(prepare) -> None: ...
