from _typeshed import Incomplete
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import Point as Point

from .common import all_types as all_types
from .common import empty as empty
from .common import geometry_collection as geometry_collection
from .common import ignore_invalid as ignore_invalid
from .common import line_string as line_string
from .common import linear_ring as linear_ring
from .common import point as point
from .common import polygon as polygon

UNARY_PREDICATES: Incomplete
BINARY_PREDICATES: Incomplete
BINARY_PREPARED_PREDICATES: Incomplete
XY_PREDICATES: Incomplete

def test_unary_array(geometry, func) -> None: ...
def test_unary_with_kwargs(func) -> None: ...
def test_unary_missing(func) -> None: ...
def test_binary_array(a, func) -> None: ...
def test_binary_with_kwargs(func) -> None: ...
def test_binary_missing(func) -> None: ...
def test_binary_empty_result() -> None: ...
def test_xy_array(a, func, func_bin) -> None: ...
def test_xy_array_broadcast(a, func, func_bin) -> None: ...
def test_xy_array_2D(func) -> None: ...
def test_xy_prepared(func, func_bin) -> None: ...
def test_xy_with_kwargs(func) -> None: ...
def test_xy_missing(func) -> None: ...
def test_equals_exact_tolerance() -> None: ...
def test_dwithin() -> None: ...
def test_is_closed(geometry, expected) -> None: ...
def test_relate() -> None: ...
def test_relate_none(g1, g2) -> None: ...
def test_relate_pattern() -> None: ...
def test_relate_pattern_empty() -> None: ...
def test_relate_pattern_none(g1, g2) -> None: ...
def test_relate_pattern_incorrect_length() -> None: ...
def test_relate_pattern_non_string(pattern) -> None: ...
def test_relate_pattern_non_scalar() -> None: ...
def test_is_ccw(geom, expected) -> None: ...
def test_binary_prepared(a, func) -> None: ...
def test_is_prepared_true(geometry) -> None: ...
def test_is_prepared_false(geometry) -> None: ...
def test_contains_properly() -> None: ...
