from _typeshed import Incomplete
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import MultiPolygon as MultiPolygon
from shapely import Point as Point
from shapely import Polygon as Polygon
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import all_types as all_types
from .common import empty_line_string as empty_line_string
from .common import empty_line_string_z as empty_line_string_z
from .common import empty_point as empty_point
from .common import empty_point_z as empty_point_z
from .common import empty_polygon as empty_polygon
from .common import geometry_collection as geometry_collection
from .common import geometry_collection_z as geometry_collection_z
from .common import line_string as line_string
from .common import line_string_nan as line_string_nan
from .common import line_string_z as line_string_z
from .common import linear_ring as linear_ring
from .common import multi_line_string as multi_line_string
from .common import multi_line_string_z as multi_line_string_z
from .common import multi_point as multi_point
from .common import multi_point_z as multi_point_z
from .common import multi_polygon as multi_polygon
from .common import multi_polygon_z as multi_polygon_z
from .common import point as point
from .common import point_z as point_z
from .common import polygon as polygon
from .common import polygon_with_hole as polygon_with_hole
from .common import polygon_with_hole_z as polygon_with_hole_z
from .common import polygon_z as polygon_z

def test_get_num_points() -> None: ...
def test_get_num_interior_rings() -> None: ...
def test_get_num_geometries() -> None: ...
def test_get_point_non_linestring(geom) -> None: ...
def test_get_point(geom) -> None: ...
def test_get_exterior_ring_non_polygon(geom) -> None: ...
def test_get_exterior_ring() -> None: ...
def test_get_interior_ring_non_polygon(geom) -> None: ...
def test_get_interior_ring() -> None: ...
def test_get_geometry_simple(geom) -> None: ...
def test_get_geometry_collection(geom) -> None: ...
def test_get_type_id() -> None: ...
def test_get_dimensions() -> None: ...
def test_get_coordinate_dimension() -> None: ...
def test_get_num_coordinates() -> None: ...
def test_get_srid() -> None: ...
def test_get_set_srid() -> None: ...
def test_get_xyz_no_point(func, geom) -> None: ...
def test_get_x() -> None: ...
def test_get_y() -> None: ...
def test_get_z() -> None: ...
def test_get_z_2d() -> None: ...
def test_new_from_wkt(geom) -> None: ...
def test_adapt_ptr_raises() -> None: ...
def test_hash_same_equal(geom): ...
def test_hash_same_not_equal(geom): ...
def test_eq(geom): ...
def test_neq(geom): ...
def test_set_unique(geom): ...
def test_eq_nan() -> None: ...
def test_neq_nan() -> None: ...
def test_set_nan() -> None: ...
def test_set_nan_same_objects() -> None: ...
def test_get_parts(geom) -> None: ...
def test_get_parts_array() -> None: ...
def test_get_parts_geometry_collection_multi() -> None: ...
def test_get_parts_return_index() -> None: ...
def test_get_parts_invalid_dimensions(geom) -> None: ...
def test_get_parts_non_multi(geom) -> None: ...
def test_get_parts_None(geom) -> None: ...
def test_get_parts_invalid_geometry(geom) -> None: ...
def test_get_rings(geom) -> None: ...
def test_get_rings_holes() -> None: ...
def test_get_rings_return_index() -> None: ...
def test_get_rings_invalid_dimensions(geom) -> None: ...
def test_get_precision() -> None: ...
def test_get_precision_none() -> None: ...
def test_set_precision(mode) -> None: ...
def test_set_precision_drop_coords() -> None: ...
def test_set_precision_z(mode) -> None: ...
def test_set_precision_nan(mode) -> None: ...
def test_set_precision_none() -> None: ...
def test_set_precision_grid_size_nan() -> None: ...
def test_set_precision_collapse(geometry, mode, expected) -> None: ...
def test_set_precision_intersection() -> None: ...
def set_precision_preserve_topology(preserve_topology) -> None: ...
def set_precision_pointwise_pre_310() -> None: ...
def set_precision_illegal_flags(flags) -> None: ...
def test_empty() -> None: ...

geometry_collection_2: Incomplete
empty_geom_mark: Incomplete

def test_force_2d(geom, expected) -> None: ...
def test_force_3d(geom, expected) -> None: ...
