from _typeshed import Incomplete
from shapely import LineString as LineString
from shapely import MultiLineString as MultiLineString
from shapely import Point as Point
from shapely import box as box
from shapely import get_coordinates as get_coordinates
from shapely.plotting import patch_from_polygon as patch_from_polygon
from shapely.plotting import plot_line as plot_line
from shapely.plotting import plot_points as plot_points
from shapely.plotting import plot_polygon as plot_polygon

def test_patch_from_polygon() -> None: ...
def test_patch_from_polygon_with_interior() -> None: ...
def test_patch_from_multipolygon() -> None: ...
def test_plot_polygon() -> None: ...
def test_plot_polygon_with_interior() -> None: ...
def test_plot_multipolygon() -> None: ...
def test_plot_line() -> None: ...
def test_plot_multilinestring() -> None: ...
def test_plot_points() -> None: ...
def equal_color(actual, expected, alpha: Incomplete | None = ...): ...
