import shapely
from _typeshed import Incomplete
from shapely import LinearRing as LinearRing
from shapely import Polygon as Polygon
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import empty_point as empty_point
from .common import line_string as line_string
from .common import linear_ring as linear_ring
from .common import point as point
from .common import polygon as polygon

pnts = shapely.points
lstrs = shapely.linestrings
geom_coll = shapely.geometrycollections

def test_invalid_coordinates(func, coordinates) -> None: ...
def test_invalid_geometries(func, geometries) -> None: ...
def test_invalid_indices_simple(func, indices) -> None: ...

non_writeable: Incomplete

def test_invalid_out(func, out) -> None: ...
def test_points_invalid() -> None: ...
def test_points() -> None: ...
def test_points_no_index_raises() -> None: ...
def test_points_out(indices, expected) -> None: ...
def test_linestrings(coordinates, indices, expected) -> None: ...
def test_linestrings_invalid() -> None: ...
def test_linestrings_out(indices, expected) -> None: ...
def test_linearrings(coordinates) -> None: ...
def test_linearrings_invalid(coordinates) -> None: ...
def test_linearrings_unclosed_all_coords_equal() -> None: ...
def test_linearrings_out(indices, expected) -> None: ...
def test_linearrings_buffer(dim, order) -> None: ...

hole_1: Incomplete
hole_2: Incomplete
poly: Incomplete
poly_empty: Incomplete
poly_hole_1: Incomplete
poly_hole_2: Incomplete
poly_hole_1_2: Incomplete

def test_polygons(rings, indices, expected) -> None: ...
def test_polygons_out(indices, expected) -> None: ...
def test_invalid_indices_collections(func, indices) -> None: ...
def test_geometrycollections(geometries, indices, expected) -> None: ...
def test_geometrycollections_no_index_raises() -> None: ...
def test_geometrycollections_out(indices, expected) -> None: ...
def test_multipoints() -> None: ...
def test_multilinestrings() -> None: ...
def test_multilinearrings() -> None: ...
def test_multipolygons() -> None: ...
def test_incompatible_types(geometries, func) -> None: ...
