from _typeshed import Incomplete
from shapely import Geometry as Geometry
from shapely import GeometryCollection as GeometryCollection
from shapely import GEOSException as GEOSException
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import MultiLineString as MultiLineString
from shapely import MultiPoint as MultiPoint
from shapely import MultiPolygon as MultiPolygon
from shapely import Point as Point
from shapely import Polygon as Polygon
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import all_types as all_types
from .common import empty as empty
from .common import empty_line_string as empty_line_string
from .common import empty_point as empty_point
from .common import empty_polygon as empty_polygon
from .common import ignore_invalid as ignore_invalid
from .common import line_string as line_string
from .common import multi_point as multi_point
from .common import point as point
from .common import point_z as point_z

CONSTRUCTIVE_NO_ARGS: Incomplete
CONSTRUCTIVE_FLOAT_ARG: Incomplete

def test_no_args_array(geometry, func) -> None: ...
def test_float_arg_array(geometry, func) -> None: ...
def test_snap_array(geometry, reference) -> None: ...
def test_no_args_missing(func) -> None: ...
def test_float_arg_missing(func) -> None: ...
def test_float_arg_nan(geometry, func) -> None: ...
def test_buffer_cap_style_invalid() -> None: ...
def test_buffer_join_style_invalid() -> None: ...
def test_snap_none() -> None: ...
def test_snap_nan_float(geometry) -> None: ...
def test_build_area_none() -> None: ...
def test_build_area(geom, expected) -> None: ...
def test_make_valid_none() -> None: ...
def test_make_valid(geom, expected) -> None: ...
def test_make_valid_1d(geom, expected) -> None: ...
def test_normalize(geom, expected) -> None: ...
def test_offset_curve_empty() -> None: ...
def test_offset_curve_distance_array() -> None: ...
def test_offset_curve_kwargs() -> None: ...
def test_offset_curve_non_scalar_kwargs() -> None: ...
def test_offset_curve_join_style_invalid() -> None: ...
def test_remove_repeated_points(geom, expected) -> None: ...
def test_remove_repeated_points_invalid_result(geom, tolerance) -> None: ...
def test_remove_repeated_points_none() -> None: ...
def test_remove_repeated_points_invalid_type(geom, tolerance) -> None: ...
def test_reverse(geom, expected) -> None: ...
def test_reverse_none() -> None: ...
def test_reverse_invalid_type(geom) -> None: ...
def test_clip_by_rect(geom, expected) -> None: ...
def test_clip_by_rect_polygon(geom, rect, expected) -> None: ...
def test_clip_by_rect_array(geometry) -> None: ...
def test_clip_by_rect_missing() -> None: ...
def test_clip_by_rect_empty(geom) -> None: ...
def test_clip_by_rect_non_scalar_kwargs() -> None: ...
def test_polygonize() -> None: ...
def test_polygonize_array() -> None: ...
def test_polygonize_array_axis() -> None: ...
def test_polygonize_missing() -> None: ...
def test_polygonize_full() -> None: ...
def test_polygonize_full_array() -> None: ...
def test_polygonize_full_array_axis() -> None: ...
def test_polygonize_full_missing() -> None: ...
def test_segmentize_invalid_max_segment_length(
    geometry, max_segment_length
) -> None: ...
def test_segmentize_max_segment_length_nan(geometry) -> None: ...
def test_segmentize_empty(geometry) -> None: ...
def test_segmentize_no_change(geometry) -> None: ...
def test_segmentize_none() -> None: ...
def test_segmentize(geometry, tolerance, expected) -> None: ...
def test_minimum_bounding_circle_all_types(geometry) -> None: ...
def test_minimum_bounding_circle(geometry, expected) -> None: ...
def test_oriented_envelope_all_types(geometry) -> None: ...
def test_oriented_envelope(geometry, expected) -> None: ...
def test_minimum_rotated_rectangle(geometry, expected) -> None: ...
def test_concave_hull_kwargs() -> None: ...
