from _typeshed import Incomplete
from shapely import Geometry as Geometry
from shapely import GeometryCollection as GeometryCollection
from shapely import Polygon as Polygon
from shapely.errors import UnsupportedGEOSVersionError as UnsupportedGEOSVersionError
from shapely.testing import assert_geometries_equal as assert_geometries_equal

from .common import all_types as all_types
from .common import empty as empty
from .common import geometry_collection as geometry_collection
from .common import multi_polygon as multi_polygon
from .common import point as point
from .common import polygon as polygon

all_single_types: Incomplete
SET_OPERATIONS: Incomplete
REDUCE_SET_OPERATIONS: Incomplete
REDUCE_SET_OPERATIONS_PREC: Incomplete
reduce_test_data: Incomplete
non_polygon_types: Incomplete

def test_set_operation_array(request, a, func) -> None: ...
def test_set_operations_prec_not_supported(func, grid_size) -> None: ...
def test_set_operation_prec_nonscalar_grid_size(func) -> None: ...
def test_set_operation_prec_array(a, func, grid_size) -> None: ...
def test_set_operation_reduce_1dim(n, func, related_func) -> None: ...
def test_set_operation_reduce_single_geom(func, related_func) -> None: ...
def test_set_operation_reduce_axis(func, related_func) -> None: ...
def test_set_operation_reduce_empty(func, related_func) -> None: ...
def test_set_operation_reduce_one_none(func, related_func, none_position) -> None: ...
def test_set_operation_reduce_two_none(func, related_func, none_position) -> None: ...
def test_set_operation_reduce_some_none_len2(func, related_func) -> None: ...
def test_set_operation_reduce_all_none(n, func, related_func) -> None: ...
def test_set_operation_reduce_all_none_arr(n, func, related_func) -> None: ...
def test_set_operation_prec_reduce_not_supported(
    func, related_func, grid_size
) -> None: ...
def test_set_operation_prec_reduce_nonscalar_grid_size(func, related_func) -> None: ...
def test_set_operation_prec_reduce_grid_size_nan(func, related_func) -> None: ...
def test_set_operation_prec_reduce_1dim(n, func, related_func, grid_size) -> None: ...
def test_set_operation_prec_reduce_axis(func, related_func) -> None: ...
def test_set_operation_prec_reduce_one_none(
    func, related_func, none_position
) -> None: ...
def test_set_operation_prec_reduce_two_none(
    func, related_func, none_position
) -> None: ...
def test_set_operation_prec_reduce_all_none(n, func, related_func) -> None: ...
def test_coverage_union_reduce_1dim(n) -> None: ...
def test_coverage_union_reduce_axis() -> None: ...
def test_coverage_union_overlapping_inputs() -> None: ...
def test_coverage_union_non_polygon_inputs(geom_1, geom_2) -> None: ...
def test_union_all_prec(geom, grid_size, expected) -> None: ...
def test_uary_union_alias() -> None: ...
