class hashdict(dict):
    def __hash__(self): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def clear(self) -> None: ...
    def pop(self, *args, **kwargs) -> None: ...
    def popitem(self, *args, **kwargs) -> None: ...
    def setdefault(self, *args, **kwargs) -> None: ...
    def update(self, *args, **kwargs) -> None: ...
    def __add__(self, right): ...
