from fontTools.misc.textTools import bytechr as bytechr
from fontTools.misc.textTools import byteord as byteord
from fontTools.misc.textTools import bytesjoin as bytesjoin

def decrypt(cipherstring, R): ...
def encrypt(plainstring, R): ...
def hexString(s): ...
def deHexString(h): ...
