from _typeshed import Incomplete

MAX_F2DOT14: Incomplete

def fixedToFloat(value, precisionBits): ...
def floatToFixed(value, precisionBits): ...
def floatToFixedToFloat(value, precisionBits): ...
def fixedToStr(value, precisionBits): ...
def strToFixed(string, precisionBits): ...
def strToFixedToFloat(string, precisionBits): ...
def floatToFixedToStr(value, precisionBits): ...
def ensureVersionIsLong(value): ...
def versionToFixed(value): ...
