from _typeshed import Incomplete
from fontTools.misc.textTools import tobytes as tobytes
from fontTools.misc.textTools import tostr as tostr

class Error(Exception): ...

def pack(fmt, obj): ...
def unpack(fmt, data, obj: Incomplete | None = ...): ...
def unpack2(fmt, data, obj: Incomplete | None = ...): ...
def calcsize(fmt): ...
def getformat(fmt, keep_pad_byte: bool = ...): ...
