from _typeshed import Incomplete

epoch_diff: Incomplete
DAYNAMES: Incomplete
MONTHNAMES: Incomplete

def asctime(t: Incomplete | None = ...): ...
def timestampToString(value): ...
def timestampFromString(value): ...
def timestampNow(): ...
def timestampSinceEpoch(value): ...
