from shapely import Point as Point
from shapely.coords import CoordinateSequence as CoordinateSequence
from shapely.errors import DimensionError as DimensionError

def test_from_coordinates() -> None: ...
def test_from_sequence() -> None: ...
def test_from_numpy() -> None: ...
def test_from_numpy_xy() -> None: ...
def test_from_point() -> None: ...
def test_from_generator() -> None: ...
def test_from_invalid() -> None: ...

class TestPoint:
    def test_point(self) -> None: ...
    def test_point_empty(self) -> None: ...
    def test_coords(self) -> None: ...

def test_point_immutable() -> None: ...
def test_point_array_coercion() -> None: ...
def test_numpy_empty_point_coords() -> None: ...
def test_numpy_object_array() -> None: ...
