from _typeshed import Incomplete
from shapely import GeometryCollection as GeometryCollection
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import MultiLineString as MultiLineString
from shapely import MultiPoint as MultiPoint
from shapely import MultiPolygon as MultiPolygon
from shapely import Point as Point
from shapely import Polygon as Polygon
from shapely.errors import ShapelyDeprecationWarning as ShapelyDeprecationWarning
from shapely.testing import assert_geometries_equal as assert_geometries_equal

def test_polygon() -> None: ...
def test_linestring() -> None: ...
def test_point() -> None: ...
def test_geometry_collection() -> None: ...

geometries_all_types: Incomplete

def test_setattr_disallowed(geom) -> None: ...
def test_weakrefable(geom) -> None: ...
def test_comparison_notimplemented(geom) -> None: ...
def test_base_class_not_callable() -> None: ...
def test_GeometryType_deprecated() -> None: ...
def test_type_deprecated() -> None: ...
def test_segmentize() -> None: ...
def test_reverse() -> None: ...
def test_binary_op_grid_size(op, grid_size) -> None: ...
def test_dwithin() -> None: ...
def test_contains_properly() -> None: ...
def test_constructive_properties(op) -> None: ...
def test_array_argument_binary_predicates(op) -> None: ...
def test_array_argument_binary_predicates2(op, kwargs) -> None: ...
def test_array_argument_binary_geo(op) -> None: ...
def test_array_argument_float(op) -> None: ...
def test_array_argument_linear() -> None: ...
def test_array_argument_buffer() -> None: ...
