from shapely import Point as Point
from shapely import Polygon as Polygon
from shapely.geos import geos_version as geos_version

def test_format_invalid() -> None: ...
def test_format_point() -> None: ...
def test_format_polygon() -> None: ...
