from shapely import GeometryCollection as GeometryCollection
from shapely import LineString as LineString
from shapely import Point as Point
from shapely import wkt as wkt
from shapely.geometry import shape as shape

def geometrycollection_geojson(): ...
def test_empty(geom) -> None: ...
def test_empty_subgeoms() -> None: ...
def test_child_with_deleted_parent() -> None: ...
def test_from_geojson(geometrycollection_geojson) -> None: ...
def test_geointerface(geometrycollection_geojson) -> None: ...
def test_len_raises(geometrycollection_geojson) -> None: ...
def test_numpy_object_array() -> None: ...
