from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import Point as Point
from shapely.coords import CoordinateSequence as CoordinateSequence

def test_from_coordinate_sequence() -> None: ...
def test_from_coordinate_sequence_3D() -> None: ...
def test_from_points() -> None: ...
def test_from_mix() -> None: ...
def test_from_linestring() -> None: ...
def test_from_linearring() -> None: ...
def test_from_linestring_z() -> None: ...
def test_from_generator() -> None: ...
def test_from_empty() -> None: ...
def test_from_numpy() -> None: ...
def test_numpy_empty_linestring_coords() -> None: ...
def test_numpy_object_array() -> None: ...
def test_from_invalid_dim() -> None: ...
def test_from_single_coordinate() -> None: ...

class TestLineString:
    def test_linestring(self) -> None: ...
    def test_linestring_empty(self) -> None: ...
    def test_equals_argument_order(self) -> None: ...
    def test_numpy_linestring_coords(self) -> None: ...

def test_linestring_immutable() -> None: ...
def test_linestring_array_coercion() -> None: ...
