from shapely import GeometryCollection as GeometryCollection
from shapely import LinearRing as LinearRing
from shapely import LineString as LineString
from shapely import MultiLineString as MultiLineString
from shapely import MultiPoint as MultiPoint
from shapely import MultiPolygon as MultiPolygon
from shapely import Point as Point
from shapely import Polygon as Polygon
from shapely.geometry import mapping as mapping
from shapely.geometry import shape as shape
from shapely.geometry.base import BaseGeometry as BaseGeometry
from shapely.geometry.base import EmptyGeometry as EmptyGeometry

def empty_generator(): ...

class TestEmptiness:
    def test_empty_class(self) -> None: ...
    def test_empty_base(self) -> None: ...
    def test_empty_point(self) -> None: ...
    def test_empty_multipoint(self) -> None: ...
    def test_empty_geometry_collection(self) -> None: ...
    def test_empty_linestring(self) -> None: ...
    def test_empty_multilinestring(self) -> None: ...
    def test_empty_polygon(self) -> None: ...
    def test_empty_multipolygon(self) -> None: ...
    def test_empty_linear_ring(self) -> None: ...

def test_numpy_object_array() -> None: ...
def test_shape_empty() -> None: ...
def test_empty_geometry_bounds(geom) -> None: ...
