from shapely import LineString as LineString

class TestCoords:
    def test_data_promotion(self) -> None: ...
    def test_data_destriding(self) -> None: ...

class TestCoordsGetItem:
    def test_index_2d_coords(self) -> None: ...
    def test_index_3d_coords(self) -> None: ...
    def test_index_coords_misc(self) -> None: ...
    def test_slice_2d_coords(self) -> None: ...
    def test_slice_3d_coords(self) -> None: ...

class TestXY:
    def test_arrays(self) -> None: ...
