from ._dill import _locate_object as at
from ._dill import _proxy_helper as reference

def parent(obj, objtype, ignore=...): ...
def parents(obj, objtype, depth: int = ..., ignore=...): ...
def children(obj, objtype, depth: int = ..., ignore=...): ...

refobject = at
