from _typeshed import Incomplete

def isfrommain(obj): ...
def isdynamic(obj): ...
def findsource(object): ...
def getsourcelines(object, lstrip: bool = ..., enclosing: bool = ...): ...
def getsource(
    object,
    alias: str = ...,
    lstrip: bool = ...,
    enclosing: bool = ...,
    force: bool = ...,
    builtin: bool = ...,
): ...
def indent(code, spaces: int = ...): ...
def outdent(code, spaces: Incomplete | None = ..., all: bool = ...): ...
def dumpsource(object, alias: str = ..., new: bool = ..., enclose: bool = ...): ...
def getname(obj, force: bool = ..., fqn: bool = ...): ...
def getimport(
    obj,
    alias: str = ...,
    verify: bool = ...,
    builtin: bool = ...,
    enclosing: bool = ...,
): ...
def importable(
    obj, alias: str = ..., source: Incomplete | None = ..., builtin: bool = ...
): ...

getblocks_from_history = getblocks  # type: ignore

# Names in __all__ with no definition:
#   _importable
#   _namespace
#   _wrap
