from _typeshed import Incomplete
from fontTools import ttLib as ttLib
from fontTools.misc import psCharStrings as psCharStrings
from fontTools.misc.loggingTools import deprecateFunction as deprecateFunction
from fontTools.misc.roundTools import otRound as otRound
from fontTools.pens.basePen import NullPen as NullPen

class _ClosureGlyphsT2Decompiler(psCharStrings.SimpleT2Decompiler):
    components: Incomplete
    def __init__(self, components, localSubrs, globalSubrs) -> None: ...
    def op_endchar(self, index) -> None: ...

def closure_glyphs(self, s) -> None: ...
def prune_pre_subset(self, font, options): ...
def subset_glyphs(self, s): ...
def subset_subroutines(self, subrs, gsubrs) -> None: ...
def drop_hints(self) -> None: ...

class _MarkingT2Decompiler(psCharStrings.SimpleT2Decompiler):
    def __init__(self, localSubrs, globalSubrs, private) -> None: ...
    def op_callsubr(self, index) -> None: ...
    def op_callgsubr(self, index) -> None: ...

class _DehintingT2Decompiler(psCharStrings.T2WidthExtractor):
    class Hints:
        has_hint: bool
        last_hint: int
        last_checked: int
        status: int
        has_hintmask: bool
        deletions: Incomplete
        def __init__(self) -> None: ...
    private: Incomplete
    def __init__(
        self,
        css,
        localSubrs,
        globalSubrs,
        nominalWidthX,
        defaultWidthX,
        private: Incomplete | None = ...,
    ) -> None: ...
    def execute(self, charString) -> None: ...
    def op_callsubr(self, index) -> None: ...
    def op_callgsubr(self, index) -> None: ...
    def op_hstem(self, index) -> None: ...
    def op_vstem(self, index) -> None: ...
    def op_hstemhm(self, index) -> None: ...
    def op_vstemhm(self, index) -> None: ...
    def op_hintmask(self, index): ...
    def op_cntrmask(self, index): ...
    def processHintmask(self, index) -> None: ...
    def processHint(self, index) -> None: ...
    def processSubr(self, index, subr) -> None: ...

def prune_post_subset(self, ttfFont, options): ...
def desubroutinize(self) -> None: ...
def remove_hints(self) -> None: ...
def remove_unused_subroutines(self) -> None: ...
