on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
  
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: pypa/hatch@install
    - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
      with:
        crate: resvg
    - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
      with:
        crate: usvg
    - run: hatch run python tests/test.py 1 2 3 4 5 6 7 8 9
