on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: pypa/hatch@install
    - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
      with:
        crate: resvg
    - uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
      with:
        crate: usvg
    - run: hatch run python tests/test.py 9

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      changelog: ${{ steps.release-info.outputs.changelog }}
      version: ${{ steps.release-info.outputs.version }}

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: pypa/hatch@install
    - run: hatch build

    - id: release-info
      run: |
        {
        echo 'changelog<<__EOF__'
        hatch run python -c "
        from tile_renderer.__about__ import __version__
        print('\n'.join(open('CHANGELOG.md').read().split('## v'+__version__)[1].split('\n')[1:]).split('\n##')[0])
        "
        echo __EOF__
        } >> "$GITHUB_OUTPUT"
        
        hatch run python -c "
        from tile_renderer.__about__ import __version__
        print('version=v'+__version__)
        " >> "$GITHUB_OUTPUT"
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: dist-pypi
        path: dist

    - run: |
        hatch run python -c "
        from tile_renderer.skin import Skin
        from pathlib import Path
        Skin.default().save_json(Path.cwd() / 'dist')
        "
        hatch run python -c "
        import json
        from pathlib import Path
        j = json.loads((Path.cwd() / 'dist' / 'default.skin.json').read_text())
        j['font_files'] = []
        (Path.cwd() / 'dist' / 'default.nofontfiles.skin.json').write_text(json.dumps(j))
        "
    - run: |
        hatch run tile-renderer schema pla2 > dist/pla2.schema.json
        hatch run tile-renderer schema skin > dist/skin.schema.json
    - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
      with:
        name: dist-github
        path: dist

  github-release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist-github
          path: dist
      - uses: softprops/action-gh-release@26e8ad27a09a225049a7075d7ec1caa2df6ff332 # v2.6.0
        with:
          tag_name: ${{ needs.build.outputs.version }}
          body: ${{ needs.build.outputs.changelog }}
          files: dist/*

  pypi:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/tile-renderer
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: dist-pypi
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
